<div class="brand">
    <!-- toggle offscreen menu -->
    <a href="javascript:;" class="ti-menu off-left visible-xs" data-toggle="offscreen" data-move="ltr"></a>
    <!-- /toggle offscreen menu -->

    <!-- logo -->
    <a href="index.html" class="navbar-brand">
        <img src="img/logo.png" alt="">
        <span class="heading-font">
            Trackr
        </span>
    </a>
    <!-- /logo -->
</div>