<nav class="main-navigation" data-height="auto" data-size="6px" data-distance="0" data-rail-visible="true"
     data-wheel-step="10">
    <p class="nav-title">MENU</p>
    <ul class="nav">
        <!-- home -->
        <li>
            <a href="index.php">
                <i class="ti-home"></i>
                <span>Home</span>
            </a>
        </li>
        <!-- /home -->

        <li>
            <a href="school_data.php">
                <i class="ti-bookmark"></i>
                <span>School Information</span>
            </a>
        </li>

        <!-- chat -->
        <li>
            <a href="messages.php">
                <i class="ti-comment-alt"></i>
                <span>Chat</span>
            </a>
            
        </li>


        <!-- /chat -->

        <!-- STAFF -->
        <li>
            <a href="javascript:;">
                <i class="toggle-accordion"></i>
                <i class="ti-user"></i>
                <span>Manage Teachers</span>
            </a>
            <ul class="sub-menu">
                <li>
                    <a href="add_teacher.php">
                        <span>Add Teacher</span>
                    </a>
                </li>
                <li>
                    <a href="a_activate_staff.php">
                        <span>Authorize Teachers</span>
                    </a>
                </li>
                
            </ul>
        </li>
        <!-- /STAFF -->


        <li>
            <a href="javascript:;">
                <i class="toggle-accordion"></i>
                <i class="ti-layout-grid2-alt"></i>
                <span>Manage Classes</span>
            </a>
            <ul class="sub-menu">
                <li>
                    <a href="class.php">
                        <span>Navigate Classes</span>
                    </a>
                </li>
                <li>
                    <a href="classes.php">
                        <span>Manage Classes</span>
                    </a>
                </li>
                <li>
                    <a href="a_assign_staff.php">
                        <span>Assign Teachers to Class</span>
                    </a>
                </li>
                
            </ul>
        </li>


        <!-- news letter -->
        <li>
            <a href="javascript:;">
                <i class="ti-announcement"></i>
                <i class="toggle-accordion"></i>
                <span>News Letter</span>
            </a>
            <ul class="sub-menu">
                <li>
                    <a href="news_letter.php">
                        <span>Preview/Edit a Newsletter</span>
                    </a>
                </li>
                <li>
                    <a href="news_letter.php?action=create">
                        <span>Send Newsletter</span>
                    </a>
                </li>
            </ul>


        </li>
        <!-- /news -->

        <!-- exam scores -->

        <!-- /exam scores -->


        <!-- students -->
        <li>
            <a href="javascript:;">
                <i class="ti-user"></i>
                <i class="toggle-accordion"></i>
                <span>Students and Exams</span>
            </a>

            <ul class="sub-menu">
                <li>
                    <a href="students.php">
                        <span>Students</span>
                    </a>
                </li>

                <li>
                    <a href="a_assessment.php">
                        <span>Broadsheet</span>
                    </a>
                </li>

            </ul>


        </li>
        <!-- /students -->

        <!-- rules -->
        <li>
            <a href="a_rules_reg.php">
                <i class="fa fa-gavel"></i>
                <span>Rules And Regulations</span>
            </a>
        </li>
        <!-- /rules -->

        <!--SIGNOUT-->
        <li>
            <a href="signout.php">
                <i class="fa fa-power-off"></i>
                <span>Log Out!</span>
            </a>
        </li>
        <!--SIGNOUT-->



    </ul>

</nav>