<nav class="main-navigation" data-height="auto" data-size="6px" data-distance="0" data-rail-visible="true"
     data-wheel-step="10">
    <p class="nav-title">MENU</p>
    <ul class="nav">

        <li>
            <a href="index.php">
                <i class="ti-home"></i>
                <span title="Edit the behaviours of students in your class">Home (Behaviour)</span>
            </a>
        </li>

        <li>
            <a href="messages.php">
                <i class="ti-comment-alt"></i>
                <span title="Chat with parents of students in your class">Chats</span>
            </a>
        </li>

        <li>
            <a href="javascript:;">
                <i class="toggle-accordion"></i>
                <i class="ti-user"></i>
                <span title="Manage affairs of students in your class">Manage Students</span>
            </a>

            <ul class="sub-menu">

                <li>
                    <a href="mark_attendance.php">
                        <i class="ti-check-box"></i>
                        <span title="Mark students attendance every morning">Mark Attendance</span>
                    </a>
                </li>

                <li>
                    <a href="add_student.php">
                        <i class="ti-user"></i>
                        <span title="You can edit or add new students to your class">View and Edit Students</span>
                    </a>
                </li>

            </ul>


        </li>

        <li>
            <a href="class.php">
                <i class="ti-direction-alt"></i>
                <span title="Browse through classes for a particular person">Navigate Classes</span>
            </a>
        </li>

        <li>
            <a href="t_set_scores.php">
                <i class="ti-ruler-pencil"></i>
                <span title="Set exam scores of this term and other terms">Examinations</span>
            </a>
        </li>

        <li>
            <a href="t_set_subjects.php">
                <i class="ti-book"></i>
                <span title="Set subjects that are offered in your class">Set Subjects</span>
            </a>
        </li>

        <!--SIGNOUT-->
        <li>
            <a href="signout.php">
                <i class="fa fa-power-off"></i>
                <span>Log Out!</span>
            </a>
        </li>
        <!--SIGNOUT-->

    </ul>
</nav>