<script src="plugins/jquery-2.1.3.min.js"></script>
<script src="bootstrap/js/bootstrap.js"></script>
<script src="plugins/jquery.slimscroll.min.js"></script>
<script src="plugins/jquery.easing.min.js"></script>
<script src="plugins/appear/jquery.appear.js"></script>
<script src="plugins/jquery.placeholder.js"></script>
<script src="plugins/jquery.cookie.js"></script>
<script src="plugins/fastclick.js"></script>
<script src="plugins/moment.js"></script>
<script src="plugins/livestamp/livestamp.min.js"></script>
<script src="plugins/toastr/toastr.min.js"></script>
<script src="js/functions.js"></script>
<script src="js/my-script.js"></script>


<script src="js/ajax-chat-check-notif.js"></script>
<audio id="sound-notification">
    <source src="media/sound/notif.mp3" type="audio/mpeg">
</audio>