<!-- meta -->
<meta charset="utf-8">
<meta name="description" content="Grade Access : Solution for African Schools">
<meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no' />
<!-- /meta -->
<!-- page level plugin styles -->

<!-- /page level plugin styles -->
<!-- core styles -->
<link rel="stylesheet" href="bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" href="css/font-awesome.css">
<link rel="stylesheet" href="css/themify-icons.css">
<link rel="stylesheet" href="css/animate.min.css">
<link rel="stylesheet" href="plugins/toastr/toastr.min.css">
<!-- /core styles -->
<!-- template styles -->
<link rel="stylesheet" href="css/skins/palette.css" id="skin">
<link rel="stylesheet" href="css/fonts/font.css">
<link rel="stylesheet" href="css/main.css">
<link rel="stylesheet" href="css/gradeaccess.css">
<style type="text/css" media="print">
  @page { size: landscape; }
</style>
<link rel="icon" href="favicon.gif">
<!-- template styles -->
<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]
<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
[endif]-->
<!-- load modernizer -->
<script src="plugins/modernizr.js"></script>
<!--  -->
    